# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs


name: STEETDICO FRONT DEV
run-name: Deploy to streetdico dev by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@4.2.2
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4.1.0
      with:
        node-version: 18.x
        cache: 'npm'
    - run: npm i
    - run: npm run build --if-present

# Uploads the artefact in path     
    - uses: actions/upload-artifact@v4.4.3
      with:
          name: streetdico-front-dev
          path: ./dist
       
       
# Deploy on dev
  deployment:
    environment: dev
    runs-on: ubuntu-latest
    needs: build
     
    steps:
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Download artefact
          uses: actions/download-artifact@v4.1.8
          with:
            name: streetdico-front-dev
            path: ./dist
            
        - name: Copy files to the test website with the AWS CLI
          run:  |
            aws s3 sync /home/runner/work/streetdico-front/streetdico-front/dist/apps/streetdico-front/ s3://sd-angular-frontend
          
